# Generated by Django 6.0.7 on 2026-08-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(blank=True, default="Python", max_length=50),
        ),
    ]
