# Generated by Django 4.2.30 on 2026-09-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_preferred_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="college",
        ),
        migrations.RemoveField(
            model_name="user",
            name="degree",
        ),
        migrations.RemoveField(
            model_name="user",
            name="github",
        ),
        migrations.RemoveField(
            model_name="user",
            name="graduation_year",
        ),
        migrations.RemoveField(
            model_name="user",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="specialization",
        ),
    ]
