import jsPDF from "jspdf";
import { FinalReport } from "../types";

export function generateCandidatePDFReport(report: FinalReport) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header Banner Background
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 45, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text("AI INTERVIEW PERFORMANCE REPORT", 14, y);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text("Confidential Evaluation & Skill Breakdown • Generated by AI Interview Simulator", 14, y + 8);

  y = 55;

  // Candidate Details Section
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.roundedRect(14, y, pageWidth - 28, 38, 3, 3, "FD");

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 41, 59);
  doc.text("CANDIDATE INFORMATION", 18, y + 8);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);

  doc.text(`Candidate Name: ${report.candidateName}`, 18, y + 16);
  doc.text(`Email Address: ${report.candidateEmail}`, 18, y + 22);
  doc.text(`Date of Assessment: ${new Date(report.date).toLocaleDateString()}`, 18, y + 28);

  doc.text(`Target Company: ${report.company}`, 110, y + 16);
  doc.text(`Target Role: ${report.role}`, 110, y + 22);
  doc.text(`Difficulty & Type: ${report.difficulty} (${report.type})`, 110, y + 28);

  y += 46;

  // Overall Score & Hiring Verdict
  doc.setFillColor(240, 253, 244); // emerald-50
  doc.setDrawColor(187, 247, 208); // emerald-200
  doc.roundedRect(14, y, pageWidth - 28, 24, 3, 3, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(5, 150, 105);
  doc.text(`OVERALL SCORE: ${report.overallScore} / 100`, 18, y + 10);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(55, 65, 81);
  const verdict =
    report.overallScore >= 80
      ? "RECOMMENDED FOR NEXT ROUND (STRONG PASS)"
      : report.overallScore >= 65
      ? "POTENTIAL FIT (REQUIRES TARGETED PRACTICE)"
      : "NEEDS FURTHER PREPARATION";
  doc.text(`Hiring Assessment Verdict: ${verdict}`, 18, y + 17);

  y += 32;

  // Radar Metrics Breakdown
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text("SKILL COMPETENCY BREAKDOWN", 14, y);
  y += 6;

  const metrics = [
    { label: "Technical Competency", score: report.radarMetrics?.technical || 80 },
    { label: "Communication & Clarity", score: report.radarMetrics?.communication || 80 },
    { label: "Problem Solving & Logic", score: report.radarMetrics?.problemSolving || 80 },
    { label: "Confidence & Delivery", score: report.radarMetrics?.confidence || 80 },
    { label: "System Design & Culture Fit", score: report.radarMetrics?.systemDesignCulture || 80 },
  ];

  metrics.forEach((m) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);
    doc.text(m.label, 14, y + 4);

    // Bar background
    doc.setFillColor(226, 232, 240);
    doc.rect(80, y, 90, 5, "F");

    // Bar fill
    doc.setFillColor(79, 70, 229); // indigo-600
    doc.rect(80, y, (m.score / 100) * 90, 5, "F");

    doc.setFont("helvetica", "bold");
    doc.text(`${m.score}%`, 175, y + 4);

    y += 9;
  });

  y += 6;

  // Key Strengths
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(16, 185, 129);
  doc.text("TOP CANDIDATE STRENGTHS", 14, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);

  (report.topStrengths || []).forEach((s) => {
    const lines = doc.splitTextToSize(`• ${s}`, pageWidth - 32);
    doc.text(lines, 16, y);
    y += lines.length * 5;
  });

  y += 4;

  // Key Weaknesses
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(239, 68, 68);
  doc.text("KEY AREAS FOR IMPROVEMENT", 14, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);

  (report.keyWeaknesses || []).forEach((w) => {
    const lines = doc.splitTextToSize(`• ${w}`, pageWidth - 32);
    doc.text(lines, 16, y);
    y += lines.length * 5;
  });

  y += 6;

  // Final AI Remark
  if (y > 230) {
    doc.addPage();
    y = 20;
  }

  doc.setFillColor(243, 244, 246);
  doc.roundedRect(14, y, pageWidth - 28, 28, 3, 3, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  doc.text("AI INTERVIEWER SUMMARY REMARK", 18, y + 8);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(8.5);
  doc.setTextColor(75, 85, 99);
  const remarkLines = doc.splitTextToSize(`"${report.finalAiRemark}"`, pageWidth - 36);
  doc.text(remarkLines, 18, y + 15);

  y += 36;

  // Detailed Questions & Answers
  if (y > 220) {
    doc.addPage();
    y = 20;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text("QUESTION BY QUESTION BREAKDOWN", 14, y);
  y += 8;

  (report.questions || []).forEach((q, idx) => {
    if (y > 240) {
      doc.addPage();
      y = 20;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(79, 70, 229);
    doc.text(`Q${idx + 1}: ${q.question}`, 14, y);
    y += 5;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(51, 65, 85);
    const ansLines = doc.splitTextToSize(`Candidate Answer: ${q.userAnswer || "No answer provided"}`, pageWidth - 30);
    doc.text(ansLines, 16, y);
    y += ansLines.length * 4.5 + 2;

    if (q.evaluation) {
      doc.setFont("helvetica", "bold");
      doc.setTextColor(16, 185, 129);
      doc.text(`Score: ${q.evaluation.score}/100 | Feedback: ${q.evaluation.feedback}`, 16, y);
      y += 6;
    }

    y += 4;
  });

  // Footer on page
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 25, 287);
    doc.text("AI Interview Simulator — B.Tech Computer Science Final Project Demonstration", 14, 287);
  }

  // Save PDF
  const filename = `${report.company}_${report.role}_Report_${report.candidateName.replace(/\s+/g, "_")}.pdf`;
  doc.save(filename);
}
