import jsPDF from "jspdf";
import { FinalReport } from "../types";

export function generateCandidatePDFReport(report: FinalReport) {
  try {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    const left = 14;
    const contentWidth = pageWidth - 28;

    let y = 20;

    const addPageIfNeeded = (requiredSpace = 20) => {
      if (y + requiredSpace > 275) {
        doc.addPage();
        y = 20;
      }
    };

    const safeText = (value: unknown, fallback = "Not available") => {
      if (
        value === null ||
        value === undefined ||
        String(value).trim() === ""
      ) {
        return fallback;
      }

      return String(value);
    };

    const candidateName = safeText(
      report.candidateName,
      "Not available"
    );

    const candidateEmail = safeText(
      report.candidateEmail
    );

    const company = safeText(
      report.company,
      "Company"
    );

    const role = safeText(
      report.role,
      "Role"
    );

    const difficulty = safeText(
      report.difficulty
    );

    const interviewType = safeText(
      report.type
    );

    let assessmentDate = "Completed";

    if (report.date) {
      const parsedDate = new Date(report.date);

      if (!Number.isNaN(parsedDate.getTime())) {
        assessmentDate =
          parsedDate.toLocaleDateString();
      }
    }

    // ============================
    // HEADER
    // ============================

    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageWidth, 45, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(21);
    doc.setTextColor(255, 255, 255);

    doc.text(
      "AI INTERVIEW PERFORMANCE REPORT",
      left,
      y
    );

    doc.setFont(
      "helvetica",
      "normal"
    );

    doc.setFontSize(9);
    doc.setTextColor(
      148,
      163,
      184
    );

    doc.text(
      "Generated by AI Interview Simulator",
      left,
      y + 8
    );

    y = 55;

    // ============================
    // CANDIDATE INFORMATION
    // ============================

    doc.setFillColor(
      248,
      250,
      252
    );

    doc.setDrawColor(
      226,
      232,
      240
    );

    doc.roundedRect(
      left,
      y,
      contentWidth,
      40,
      3,
      3,
      "FD"
    );

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.setFontSize(11);

    doc.setTextColor(
      30,
      41,
      59
    );

    doc.text(
      "CANDIDATE INFORMATION",
      18,
      y + 8
    );

    doc.setFont(
      "helvetica",
      "normal"
    );

    doc.setFontSize(9);

    doc.setTextColor(
      71,
      85,
      105
    );

    doc.text(
      `Candidate: ${candidateName}`,
      18,
      y + 16
    );

    doc.text(
      `Email: ${candidateEmail}`,
      18,
      y + 23
    );

    doc.text(
      `Date: ${assessmentDate}`,
      18,
      y + 30
    );

    doc.text(
      `Company: ${company}`,
      110,
      y + 16
    );

    doc.text(
      `Role: ${role}`,
      110,
      y + 23
    );

    doc.text(
      `Difficulty: ${difficulty}`,
      110,
      y + 30
    );

    y += 48;

    // ============================
    // OVERALL SCORE
    // ============================

    const overallScore =
      Number(report.overallScore) || 0;

    doc.setFillColor(
      240,
      253,
      244
    );

    doc.setDrawColor(
      187,
      247,
      208
    );

    doc.roundedRect(
      left,
      y,
      contentWidth,
      26,
      3,
      3,
      "FD"
    );

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.setFontSize(14);

    doc.setTextColor(
      5,
      150,
      105
    );

    doc.text(
      `OVERALL SCORE: ${overallScore} / 100`,
      18,
      y + 10
    );

    let verdict =
      "NEEDS FURTHER PREPARATION";

    if (overallScore >= 80) {
      verdict =
        "RECOMMENDED FOR NEXT ROUND";
    } else if (
      overallScore >= 65
    ) {
      verdict =
        "POTENTIAL FIT - TARGETED PRACTICE RECOMMENDED";
    }

    doc.setFont(
      "helvetica",
      "normal"
    );

    doc.setFontSize(9);

    doc.setTextColor(
      55,
      65,
      81
    );

    doc.text(
      `Assessment: ${verdict}`,
      18,
      y + 18
    );

    y += 35;

    // ============================
    // COMPETENCY SCORES
    // ============================

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.setFontSize(12);

    doc.setTextColor(
      30,
      41,
      59
    );

    doc.text(
      "SKILL COMPETENCY BREAKDOWN",
      left,
      y
    );

    y += 8;

    const metrics = [
      {
        label:
          "Technical Competency",
        score:
          report.radarMetrics
            ?.technical ?? 0,
      },
      {
        label:
          "Communication",
        score:
          report.radarMetrics
            ?.communication ?? 0,
      },
      {
        label:
          "Problem Solving",
        score:
          report.radarMetrics
            ?.problemSolving ?? 0,
      },
      {
        label:
          "Confidence",
        score:
          report.radarMetrics
            ?.confidence ?? 0,
      },
      {
        label:
          "System Design / Culture",
        score:
          report.radarMetrics
            ?.systemDesignCulture ??
          0,
      },
    ];

    metrics.forEach(
      (metric) => {
        const score = Math.min(
          100,
          Math.max(
            0,
            Number(metric.score) ||
              0
          )
        );

        doc.setFont(
          "helvetica",
          "normal"
        );

        doc.setFontSize(9);

        doc.setTextColor(
          51,
          65,
          85
        );

        doc.text(
          metric.label,
          left,
          y + 4
        );

        doc.setFillColor(
          226,
          232,
          240
        );

        doc.rect(
          80,
          y,
          90,
          5,
          "F"
        );

        doc.setFillColor(
          79,
          70,
          229
        );

        doc.rect(
          80,
          y,
          (score / 100) * 90,
          5,
          "F"
        );

        doc.setFont(
          "helvetica",
          "bold"
        );

        doc.text(
          `${score}%`,
          175,
          y + 4
        );

        y += 9;
      }
    );

    y += 6;

    // ============================
    // STRENGTHS
    // ============================

    addPageIfNeeded(30);

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.setFontSize(11);

    doc.setTextColor(
      16,
      185,
      129
    );

    doc.text(
      "TOP STRENGTHS",
      left,
      y
    );

    y += 7;

    doc.setFont(
      "helvetica",
      "normal"
    );

    doc.setFontSize(9);

    doc.setTextColor(
      51,
      65,
      85
    );

    const strengths =
      report.topStrengths || [];

    if (strengths.length === 0) {
      doc.text(
        "No specific strengths provided.",
        16,
        y
      );

      y += 6;
    } else {
      strengths.forEach(
        (strength) => {
          addPageIfNeeded(15);

          const lines =
            doc.splitTextToSize(
              `• ${strength}`,
              contentWidth - 4
            );

          doc.text(
            lines,
            16,
            y
          );

          y +=
            lines.length * 5 +
            2;
        }
      );
    }

    y += 5;

    // ============================
    // IMPROVEMENTS
    // ============================

    addPageIfNeeded(30);

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.setFontSize(11);

    doc.setTextColor(
      239,
      68,
      68
    );

    doc.text(
      "AREAS FOR IMPROVEMENT",
      left,
      y
    );

    y += 7;

    doc.setFont(
      "helvetica",
      "normal"
    );

    doc.setFontSize(9);

    doc.setTextColor(
      51,
      65,
      85
    );

    const weaknesses =
      report.keyWeaknesses || [];

    if (weaknesses.length === 0) {
      doc.text(
        "No specific weaknesses provided.",
        16,
        y
      );

      y += 6;
    } else {
      weaknesses.forEach(
        (weakness) => {
          addPageIfNeeded(15);

          const lines =
            doc.splitTextToSize(
              `• ${weakness}`,
              contentWidth - 4
            );

          doc.text(
            lines,
            16,
            y
          );

          y +=
            lines.length * 5 +
            2;
        }
      );
    }

    y += 6;

    // ============================
    // AI REMARK
    // ============================

    addPageIfNeeded(35);

    const remark =
      safeText(
        report.finalAiRemark,
        "Interview evaluation completed."
      );

    const remarkLines =
      doc.splitTextToSize(
        remark,
        contentWidth - 10
      );

    const remarkHeight =
      Math.max(
        30,
        remarkLines.length * 5 +
          18
      );

    doc.setFillColor(
      243,
      244,
      246
    );

    doc.roundedRect(
      left,
      y,
      contentWidth,
      remarkHeight,
      3,
      3,
      "F"
    );

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.setFontSize(10);

    doc.setTextColor(
      30,
      41,
      59
    );

    doc.text(
      "AI INTERVIEWER SUMMARY",
      18,
      y + 8
    );

    doc.setFont(
      "helvetica",
      "italic"
    );

    doc.setFontSize(8.5);

    doc.setTextColor(
      75,
      85,
      99
    );

    doc.text(
      remarkLines,
      18,
      y + 16
    );

    y += remarkHeight + 10;

    // ============================
    // QUESTIONS
    // ============================

    addPageIfNeeded(25);

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.setFontSize(12);

    doc.setTextColor(
      30,
      41,
      59
    );

    doc.text(
      "QUESTION BY QUESTION BREAKDOWN",
      left,
      y
    );

    y += 10;

    const questions =
      report.questions || [];

    questions.forEach(
      (question, index) => {
        addPageIfNeeded(35);

        const questionLines =
          doc.splitTextToSize(
            `Q${index + 1}: ${safeText(
              question.question
            )}`,
            contentWidth
          );

        doc.setFont(
          "helvetica",
          "bold"
        );

        doc.setFontSize(9.5);

        doc.setTextColor(
          79,
          70,
          229
        );

        doc.text(
          questionLines,
          left,
          y
        );

        y +=
          questionLines.length *
            5 +
          3;

        addPageIfNeeded(20);

        const answerLines =
          doc.splitTextToSize(
            `Candidate Answer: ${safeText(
              question.userAnswer,
              "No answer provided"
            )}`,
            contentWidth - 4
          );

        doc.setFont(
          "helvetica",
          "normal"
        );

        doc.setFontSize(8.5);

        doc.setTextColor(
          51,
          65,
          85
        );

        doc.text(
          answerLines,
          16,
          y
        );

        y +=
          answerLines.length *
            4.5 +
          3;

        if (question.evaluation) {
          addPageIfNeeded(20);

          doc.setFont(
            "helvetica",
            "bold"
          );

          doc.setTextColor(
            16,
            185,
            129
          );

          doc.text(
            `Score: ${
              question.evaluation
                .score ?? 0
            }/100`,
            16,
            y
          );

          y += 5;

          const feedbackLines =
            doc.splitTextToSize(
              `Feedback: ${safeText(
                question
                  .evaluation
                  .feedback
              )}`,
              contentWidth - 4
            );

          doc.setFont(
            "helvetica",
            "normal"
          );

          doc.setTextColor(
            51,
            65,
            85
          );

          doc.text(
            feedbackLines,
            16,
            y
          );

          y +=
            feedbackLines.length *
              4.5 +
            3;
        }

        y += 5;
      }
    );

    // ============================
    // FOOTERS
    // ============================

    const pageCount =
      doc.getNumberOfPages();

    for (
      let page = 1;
      page <= pageCount;
      page++
    ) {
      doc.setPage(page);

      doc.setFont(
        "helvetica",
        "normal"
      );

      doc.setFontSize(8);

      doc.setTextColor(
        156,
        163,
        175
      );

      doc.text(
        `Page ${page} of ${pageCount}`,
        pageWidth - 35,
        pageHeight - 8
      );

      doc.text(
        "AI Interview Simulator",
        left,
        pageHeight - 8
      );
    }

    // ============================
    // DOWNLOAD
    // ============================

    const safeCompany =
      company.replace(
        /[^a-zA-Z0-9-_]/g,
        "_"
      );

    const safeRole =
      role.replace(
        /[^a-zA-Z0-9-_]/g,
        "_"
      );

    const safeCandidate =
      candidateName.replace(
        /[^a-zA-Z0-9-_]/g,
        "_"
      );

    const filename =
      `${safeCompany}_${safeRole}_${safeCandidate}_Interview_Report.pdf`;

    doc.save(filename);
  } catch (error) {
    console.error(
      "PDF generation failed:",
      error
    );

    alert(
      "Unable to generate the PDF report. Please try again."
    );
  }
}