# Generated by Django 6.0.7 on 2026-08-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_interviewanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="end_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="end_reason",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="feedback_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="feedback_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="status",
            field=models.CharField(default="in_progress", max_length=20),
        ),
    ]
