# Generated by Django 6.0.7 on 2026-08-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_interviewsession_end_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewanswer",
            name="improvements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="strengths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="time_spent_seconds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="camera_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="camera_feedback",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="communication_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="company",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="improvements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="preferred_languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="role",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="strengths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="technical_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="weaknesses",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
