# Generated by Django 6.0.7 on 2026-08-08 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.CharField(max_length=120)),
                ("question_title", models.CharField(max_length=255)),
                ("question_type", models.CharField(max_length=50)),
                (
                    "topic_or_language",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("difficulty", models.CharField(blank=True, default="", max_length=20)),
                ("user_answer", models.TextField(blank=True, default="")),
                ("submitted_code", models.TextField(blank=True, default="")),
                (
                    "programming_language",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("score", models.FloatField(default=0)),
                ("feedback", models.TextField(blank=True, default="")),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("improvements", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "question_id"),
                        name="unique_user_practice_question",
                    )
                ],
            },
        ),
    ]
