# Generated by Django 6.0.7 on 2026-08-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="practiceattempt",
            name="question_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
