# Generated by Django 6.0.7 on 2026-08-09 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_practiceattempt_question_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewPracticeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(default="Tell Me About Yourself", max_length=120),
                ),
                ("question", models.CharField(max_length=500)),
                ("transcript", models.TextField(blank=True, default="")),
                ("camera_used", models.BooleanField(default=False)),
                ("overall_score", models.FloatField(default=0)),
                ("content_score", models.FloatField(default=0)),
                ("structure_score", models.FloatField(default=0)),
                ("clarity_score", models.FloatField(default=0)),
                ("communication_score", models.FloatField(default=0)),
                ("feedback", models.TextField(blank=True, default="")),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("improvements", models.JSONField(blank=True, default=list)),
                ("better_answer", models.TextField(blank=True, default="")),
                ("camera_feedback", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_practice_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
