# Generated by Django 6.0.7 on 2026-08-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_interviewpracticeattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.CharField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("question_type", models.CharField(max_length=50)),
                (
                    "topic_or_language",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("difficulty", models.CharField(blank=True, default="", max_length=20)),
                ("question", models.TextField()),
                ("options", models.JSONField(blank=True, default=list)),
                ("correct_answer", models.TextField(blank=True, default="")),
                ("explanation", models.TextField(blank=True, default="")),
                ("fill_blank_snippet", models.TextField(blank=True, default="")),
                ("fill_blank_answer", models.TextField(blank=True, default="")),
                ("initial_code", models.TextField(blank=True, default="")),
                ("language_templates", models.JSONField(blank=True, default=dict)),
                ("hints", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
